[package]
name = "rust-03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_aoc = { git = "https://github.com/spwitt/rust_aoc" }